# PURL configuration for https://purl.brain-bican.org/ontology/wmbo
# Whole Mouse Brain Ontology (WMBO)

idspace: WMBO
base_url: /ontology/wmbo


products:
# https://purl.brain-bican.org/ontology/wmbo/wmbo.owl
- wmbo.owl: https://github.com/Cellular-Semantics/whole_mouse_brain_ontology/releases/latest/download/wmbo.owl
- wmbo.obo: https://github.com/Cellular-Semantics/whole_mouse_brain_ontology/releases/latest/download/wmbo.obo
- wmbo.json: https://github.com/Cellular-Semantics/whole_mouse_brain_ontology/releases/latest/download/wmbo.json

term_browser: custom
example_terms:
- PCL_0000000

base_redirect: https://github.com/Cellular-Semantics/whole_mouse_brain_ontology

entries:

- exact: /wmbo-base.owl
  replacement: https://github.com/Cellular-Semantics/whole_mouse_brain_ontology/releases/latest/download/wmbo-base.owl
  
- exact: /wmbo-base.obo
  replacement: https://github.com/Cellular-Semantics/whole_mouse_brain_ontology/releases/latest/download/wmbo-base.obo

- exact: /wmbo-base.json
  replacement: https://github.com/Cellular-Semantics/whole_mouse_brain_ontology/releases/latest/download/wmbo-base.json

- exact: /wmbo-cl-comp.owl
  replacement: https://raw.githubusercontent.com/Cellular-Semantics/whole_mouse_brain_ontology/main/wmbo-cl-comp.owl

- exact: /wmbo-cl-comp.obo
  replacement: https://raw.githubusercontent.com/Cellular-Semantics/whole_mouse_brain_ontology/main/wmbo-cl-comp.obo

- exact: /wmbo-cl-comp.json
  replacement: https://raw.githubusercontent.com/Cellular-Semantics/whole_mouse_brain_ontology/main/wmbo-cl-comp.json


## generic fall-through, serve direct from github release by default
- prefix: /
  replacement: https://github.com/Cellular-Semantics/whole_mouse_brain_ontology/releases/latest/download/
