# PURL configuration for https://purl.brain-bican.org/taxonomy/CCN20230722

idspace: CCN20230722
base_url: /taxonomy/CCN20230722

products:
- CCN20230722.json: https://raw.githubusercontent.com/brain-bican/whole_mouse_brain_taxonomy/main/CCN20230722.json

base_redirect: https://brain-bican.github.io/whole_mouse_brain_taxonomy

entries:

# https://purl.brain-bican.org/taxonomy/CCN20230722/CCN20230722.json
- exact: /CCN20230722.json
  replacement: https://raw.githubusercontent.com/brain-bican/whole_mouse_brain_taxonomy/main/CCN20230722.json

# https://purl.brain-bican.org/taxonomy/CCN20230722/releases/2023-09-24/CCN20230722.json
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/brain-bican/whole_mouse_brain_taxonomy/v
  tests:
    - from: /releases/2023-09-24/
      to: https://raw.githubusercontent.com/brain-bican/whole_mouse_brain_taxonomy/v2023-09-24/

# https://purl.brain-bican.org/taxonomy/CCN20230722/CS20230722_CLAS_01.h5ad
- regex: ^/taxonomy/CCN20230722/(.*).h5ad$
  replacement: https://cellular-semantics.cog.sanger.ac.uk/public/merged_$1.h5ad
  tests:
  - from: /CCN20230722/CS20230722_CLAS_01.h5ad
    to: https://cellular-semantics.cog.sanger.ac.uk/public/merged_CS20230722_CLAS_01.h5ad

# This config should be the last item since it will catch all remaining paths
# https://purl.brain-bican.org/taxonomy/CCN20230722/CS20230722_CLAS_01
- regex: ^/taxonomy/CCN20230722/CS20230722_(.*)$
  replacement: https://brain-bican.github.io/whole_mouse_brain_taxonomy/cell_sets/CS20230722_$1
  tests:
  - from: /CCN20230722/CS20230722_CLAS_01
    to: https://brain-bican.github.io/whole_mouse_brain_taxonomy/cell_sets/CS20230722_CLAS_01
